---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_zero
  box: win2012r2

platforms:
  - name: win2012r2

suites:
  - name: default
    run_list:
      - recipe[easy-windows-chef-workstation::default]
    attributes:
