---
driver:
  name: ec2
  aws_access_key_id: ENV['AWS_ACCESS_KEY']
  aws_secret_access_key: ENV['AWS_SECRET_KEY']
  image_id: ENV['IMAGE_ID']
  security_group_ids: ENV['SECURITY_GROUP_IDS']
  subnet_id: ENV['SUBNET_ID']
  aws_ssh_key_id: ENV['AWS_SSH_KEY_ID']
  flavor_id: ENV['FLAVOR_ID']
  availability_zone: ENV['AVAILABILITY_ZONE']
  require_chef_omnibus: true

provisioner:
  name: chef_zero

platforms:
  - name: win2012r2

suites:
  - name: default
    run_list:
      - recipe[easy-windows-chef-workstation::default]
    attributes:
