name             'easy-windows-chef-workstation'
maintainer       'The Authors'
maintainer_email 'you@example.com'
license          'all_rights'
description      'Installs/Configures easy-windows-chef-workstation'
long_description 'Installs/Configures easy-windows-chef-workstation'
version          '0.1.0'
depends          'chocolatey', '= 0.3.0'
